/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      screens: {
        sm: '576px',
        md: '768px',
        lg: '992px',
        xl: '1200px',
        xxl: '1400px',
        '3xl': '1600px',
        '4xl': '1800px',
      },
      colors: {
        b10: '#CFD8FA',
        b50: '#e6f0ff',
        b75: '#96c0ff',
        b100: '#6ba6ff',
        b200: '#2b7fff',
        b300: '#0065ff',
        b400: '#0047B3',
        b500: '#003e9c',
        b900: '#1E2783',
        y50: '#fef9ea',
        y75: '#fde8a7',
        y100: '#fcdf83',
        y200: '#fad14d',
        y300: '#f9c729',
        y400: '#ae8b1d',
        y500: '#987919',
        y600: '#FFAB00',
        v50: '#f0ebff',
        v75: '#c3adff',
        v100: '#aa8bff',
        v200: '#8659ff',
        v300: '#6d37ff',
        v400: '#4c27b3',
        v500: '#42229c',
        n10: '#fafafb',
        n20: '#f5f5f7',
        n30: '#ececef',
        n40: '#e0e0e5',
        n50: '#c3c3ce',
        n60: '#b4b4c2',
        n70: '#a8a8b8',
        n80: '#9a99ac',
        n90: '#8b8ba0',
        n100: '#7d7c94',
        n200: '#6e6e88',
        n300: '#605f7c',
        n400: '#545372',
        n500: '#454567',
        n600: '#39395d',
        n700: '#29284f',
        n800: '#1a1943',
        n900: '#0e0d39',
        g50: '#E9F9EF',
        g75: '#A4E7BD',
        g100: '#B9FF5A',
        g200: '#ABFF38',
        g300: '#22C55E',
        g400: '#118D57',
        r50: '#F9E7E4',
        r100: '#FFAC82',
        r300: '#FF5630',
        o300: '#FFAB00',
        eb50: '#C9DBF5',
        eb100: '#ADF8FF',
        eb200: '#5AF0FF',
        bg1: '#F3FFD7',
        bg2: '#C6EFF3',
        bg3: '#FFF5CC',
        bg4: '#EFF7E4',
        bg5: '#FFCCC3',
        bg6: '#FEF6E5',
        sp: 'rgba(154, 153, 172, .4)',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          1: 'hsl(var(--chart-1))',
          2: 'hsl(var(--chart-2))',
          3: 'hsl(var(--chart-3))',
          4: 'hsl(var(--chart-4))',
          5: 'hsl(var(--chart-5))',
        },
      },
      padding: {
        15: '60px',
        25: '100px',
        30: '120px',
      },
      keyframes: {
        growWidth: {
          '0%': {
            width: '0%',
          },
          '100%': {
            width: '100%',
          },
        },
        fadeIn: {
          '0%': {
            opacity: '0',
            transform: 'translateY(10px) scale(0.95)',
          },
          '100%': {
            opacity: '1',
            transform: 'translateY(0) scale(1)',
          },
        },
        fadeOut: {
          '0%': {
            opacity: '1',
            transform: 'translateY(0) scale(1)',
          },
          '100%': {
            opacity: '0',
            transform: 'translateY(10px) scale(0.95)',
          },
        },
        pulse: {
          '0%, 100%': {
            opacity: '1',
          },
          '50%': {
            opacity: '0.7',
          },
        },
        marqueeUp: {
          '0%': {
            transform: 'translateY(0)',
          },
          '100%': {
            transform: 'translateY(-50%)',
          },
        },
        marqueeDown: {
          '0%': {
            transform: 'translateY(-50%)',
          },
          '100%': {
            transform: 'translateY(0)',
          },
        },
      },
      animation: {
        'grow-width': 'growWidth 0.7s ease-out',
        'fade-in': 'fadeIn 0.3s ease-out',
        'fade-out': 'fadeOut 0.3s ease-in',
        'pulse-slow': 'pulse 3s ease-in-out infinite',
        'marquee-up': 'marqueeUp 60s linear infinite',
        'marquee-down': 'marqueeDown 60s linear infinite',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}
